export const cardProviderData = [
  { value: 'COOPBANK', label: 'COOPBANK - Ngan hang Hop tac xa Viet Nam' },
  { value: 'DBSBank', label: 'DBSBank - DBS Bank Ltd - Chi nhanh Thanh pho Ho Chi Minh' },
  { value: 'DongABank', label: 'DongABank - Ngan hang TMCP Dong A' },
  { value: 'Eximbank', label: 'Eximbank - Ngan hang TMCP Xuat Nhap khau Viet Nam' },
  { value: 'GPBank', label: 'GPBank - Ngan hang Thuong mai TNHH MTV Dau Khi Toan Cau' },
  { value: 'HDBank', label: 'HDBank - Ngan hang TMCP Phat trien Thanh pho Ho Chi Minh' },
  { value: 'HongLeong', label: 'HongLeong - Ngan hang TNHH MTV Hong Leong Viet Nam' },
  { value: 'HSBC', label: 'HSBC - Ngan hang TNHH MTV HSBC (Viet Nam)' },
  { value: 'IBKHCM', label: 'IBKHCM - Ngan hang Cong nghiep Han Quoc - Chi nhanh TP. Ho Chi Minh' },
  { value: 'IBKHN', label: 'IBKHN - Ngan hang Cong nghiep Han Quoc - Chi nhanh Ha Noi' },
  { value: 'IndovinaBank', label: 'IndovinaBank - Ngan hang TNHH Indovina' },
  { value: 'KBank', label: 'KBank - Ngan hang Dai chung TNHH Kasikornbank' },
  { value: 'KEBHanaHCM', label: 'KEBHanaHCM - Ngan hang KEB Hana – Chi nhanh Thanh pho Ho Chi Minh' },
  { value: 'KEBHANAHN', label: 'KEBHANAHN - Cong ty Tai chinh TNHH MTV Mirae Asset (Viet Nam)' },
  { value: 'KienLongBank', label: 'KienLongBank - Ngan hang TMCP Kien Long' },
  { value: 'KookminHCM', label: 'KookminHCM - Ngan hang Kookmin - Chi nhanh Thanh pho Ho Chi Minh' },
  { value: 'KookminHN', label: 'KookminHN - Ngan hang Kookmin - Chi nhanh Ha Noi' },
  { value: 'LienVietPostBank', label: 'LienVietPostBank - Ngan hang TMCP Buu Dien Lien Viet' },
  { value: 'MBBank', label: 'MBBank - Ngan hang TMCP Quan doi' },
  { value: 'MSB', label: 'MSB - Ngan hang TMCP Hang Hai' },
  { value: 'NamABank', label: 'NamABank - Ngan hang TMCP Nam A' },
  { value: 'NCB', label: 'NCB - Ngan hang TMCP Quoc Dan' },
  { value: 'Nonghyup', label: 'Nonghyup - Ngan hang Nonghyup - Chi nhanh Ha Noi' },
  { value: 'OCB', label: 'OCB - Ngan hang TMCP Phuong Dong' },
  { value: 'Oceanbank', label: 'Oceanbank - Ngan hang Thuong mai TNHH MTV Dai Duong' },
  { value: 'PGBank', label: 'PGBank - Ngan hang TMCP Xang dau Petrolimex' },
  { value: 'PublicBank', label: 'PublicBank - Ngan hang TNHH MTV Public Viet Nam' },
  { value: 'PVcomBank', label: 'PVcomBank - Ngan hang TMCP Dai Chung Viet Nam' },
  { value: 'Sacombank', label: 'Sacombank - Ngan hang TMCP Sai Gon Thuong Tin' },
  { value: 'SaigonBank', label: 'SaigonBank - Ngan hang TMCP Sai Gon Cong Thuong' },
  { value: 'SCB', label: 'SCB - Ngan hang TMCP Sai Gon' },
  { value: 'SeABank', label: 'SeABank - Ngan hang TMCP Dong Nam A' },
  { value: 'SHB', label: 'SHB - Ngan hang TMCP Sai Gon - Ha Noi' },
  { value: 'ShinhanBank', label: 'ShinhanBank - Ngan hang TNHH MTV Shinhan Viet Nam' },
  { value: 'StandardChartered', label: 'StandardChartered - Ngan hang TNHH MTV Standard Chartered Bank Viet Nam' },
  { value: 'Techcombank', label: 'Techcombank - Ngan hang TMCP Ky thuong Viet Nam' },
  { value: 'Timo', label: 'Timo - Ngan hang so Timo by Ban Viet Bank (Timo by Ban Viet Bank)' },
  { value: 'TPBank', label: 'TPBank - Ngan hang TMCP Tien Phong' },
  { value: 'Ubank', label: 'Ubank - Ngan hang TMCP Viet Nam Thinh Vuong - Ngan hang so Ubank by VPBank' },
  { value: 'UnitedOverseas', label: 'UnitedOverseas - Ngan hang United Overseas - Chi nhanh TP. Ho Chi Minh' },
  { value: 'VBSP', label: 'VBSP - Ngan hang Chinh sach Xa hoi' },
  { value: 'VIB', label: 'VIB - Ngan hang TMCP Quoc te Viet Nam' },
  { value: 'VietABank', label: 'VietABank - Ngan hang TMCP Viet A' },
  { value: 'VietBank', label: 'VietBank - Ngan hang TMCP Viet Nam Thuong Tin' },
  { value: 'VietCapitalBank', label: 'VietCapitalBank - Ngan hang TMCP Ban Viet' },
  { value: 'Vietcombank', label: 'Vietcombank - Ngan hang TMCP Ngoai Thuong Viet Nam' },
  { value: 'VietinBank', label: 'VietinBank - Ngan hang TMCP Cong thuong Viet Nam' },
  {
    value: 'ViettelMoney',
    label: 'ViettelMoney - Tong Cong ty Dich vu so Viettel - Chi nhanh tap doan cong nghiep vien thong Quan Doi'
  },
  { value: 'VNPTMoney', label: 'VNPTMoney - VNPT Money' },
  { value: 'VPBank', label: 'VPBank - Ngan hang TMCP Viet Nam Thinh Vuong' },
  { value: 'VRB', label: 'VRB - Ngan hang Lien doanh Viet - Nga' },
  { value: 'Woori', label: 'Woori - Ngan hang TNHH MTV Woori Viet Nam' }
]
