const URL = {
  URL_REGISTER_ACCOUNT: 'account/register',
  URL_LOGIN: 'account/login',
  URL_GET_PROFILE: 'account/view-profile',
  URL_REGISTER_TO_SELLER: 'account/register-to-seller',
  URL_ADD_TO_CART: 'account/add-to-cart',
  URL_GET_SELLER_PROFILE: 'account/seller-profile',
  URL_GET_CREDIT_CARD_INFO: 'account/payment-info-of-seller',
  URL_GET_CARD_PROVIDER_LIST: 'account/list-of-bank',
  URL_SET_IMAGE: 'Image/upload',
  URL_SELLER_CANCEL: 'account/cancel-to-seller',
  URL_GET_BANKS: 'account/list-of-bank',
  URL_GET_SELLER_FLOWERS: 'flower/list-all-flowers-of-seller',
  URL_CHANGE_FLOWER_STATUS: 'flower/inactive-and-active-flower',
  URL_GET_FLOWER_CATEGORIES: 'flower/list-flowers-categories',
  URL_CREATE_FLOWER_CATEGORY: 'flower/create-flower-category',
  URL_UPDATE_FLOWER_CATEGORY: 'flower/update-flower-category',
  URL_DELETE_FLOWER_CATEGORY: 'flower/delete-flower-category',
  URL_CREATE_FLOWER: 'flower/create-flower',
  URL_UPDATE_FLOWER: 'flower/update-flower',
  URL_DELETE_FLOWER: 'flower/delete-flower',
  URL_GET_FLOWER_DETAIL: 'flower/flower-detail',
  URL_GET_FLOWERS: 'flower/list-flowers',
  URL_GET_ALL_ORDERS: 'account/get-all',
  URL_GET_ORDERS_OF_SELLER: 'account/orders-of-seller',
  URL_GET_CART_ITEMS: 'account/list-cart-items',
  URL_GET_LIST_EVENTS_OF_SELLER: 'event/list-events-of-seller',
  URL_CREATE_EVENT_CATEGORY: 'event/create-event-category',
  URL_CREATE_EVENT: 'event/create-event',
  URL_UPDATE_EVENT: 'event/update-event',
  URL_DELETE_EVENT: 'event/delete-event',
  URL_UPDATE_EVENT_CATEGORY: 'event/update-event-category',
  URL_DELETE_EVENT_CATEGORY: 'event/delete-event-category',
  URL_FINISH_DELIVERY_STAGE: 'account/finish-delivering-stage'
}

export default URL
